name = "lingdu-speak-fire02"          # 你的 Worker 名
account_id = "084099361afdf1265c20c09fb3834a6f"   # 替换成你的实际 ID
workers_dev = true
main = "_worker.js"  # 关键行！告诉 wrangler 入口文件在哪
compatibility_date = "2024-01-01"  # 建议加上
