name: Deploy to Cloudflare Workers

on:
  push:
    paths:
      - '_worker.js'         # 当 _worker.js 被更新时触发部署
  workflow_dispatch:         # 支持手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          scriptPath: _worker.js
          name: youngkkk-code-v     # 你要部署的 Worker 名称
