name: Deploy to Cloudflare Workers

on:
  push:
    paths:
      - '_worker.js'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Deploy to Cloudflare Workers
        run: |
          export CLOUDFLARE_API_TOKEN="084099361afdf1265c20c09fb3834a6f"
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: "OLJgrdxKIYbsT1KmJ7-TDkiB1Rjzj3d17bjvxFNF"  # 或者直接写token，替换YOUR_CLOUDFLARE_API_TOKEN为实际值
