name: Deploy to Cloudflare Workers

on:
  push:
    paths:
      - '_worker.js'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # 使用 secrets 来传递 token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # 如果你有 accountId 也传递它
